version: '3.4'

name: gymtron
services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456Aa
      MYSQL_DATABASE: sql7761283,
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '6064:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:  # Això ha de coincidir amb el que es refereix a "volumes"
